#ifndef BATCONTROLLER_LIBRARY_PINS_HPP
#define BATCONTROLLER_LIBRARY_PINS_HPP

#define BTN_UP 0
#define BTN_DOWN 1
#define BTN_LEFT 2
#define BTN_RIGHT 3
#define BTN_A 5
#define BTN_B 4
#define BTN_C 6

#define BL_PIN 8

#endif //BATCONTROLLER_LIBRARY_PINS_HPP
